// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qksuyfgmebazmslwuqkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrc3V5ZmdtZWJhem1zbHd1cWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjQ0ODgsImV4cCI6MjA2NzcwMDQ4OH0.13BXhqdJ-beO_Iz9dVEUUp4_96b9JtcQTihsbztLkBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});